Update shouty.js to bring inline with shouty.java.
cucumber-ltd/shouty.js pull request #2
Opened 2017-01-20 04:01 UTC by temyers

Updated the shouty.js codebase to be consistent with the current shouty.java implementation

* Added Jest unit test framework, with failing unit test
* Added implementation in line with shouty.java
* Added sample scenarios, with Step Definition implementation

2017-01-22 07:42 UTC, temyers commented
The changes here are now complete and ready for review.

2017-01-23 08:49 UTC, jbpros requested changes
This is great!

I've discussed briefly with @tooky, we were wondering if we should use ES6 `class` and other goodies. I think we should, so that we teach BDD through modern JS :)

It can be done in a separate PR though.

I'm curious: why did you switch from jest to mocha @temyers?

2017-01-23 08:49 UTC, jbpros commented on .gitignore
> +jest/
Can be removed, right?

2017-01-23 08:49 UTC, jbpros commented on features/step_definitions/shout_steps.js
> +  var Shouty = require('../../lib/shouty');
Weird indentation here :)

2017-01-23 09:35 UTC, temyers commented
I switched from Jest to Mocha because Jest was taking far too long to execute the tests.  ~5s, compared to a few < 50ms with Mocha.

2017-01-23 09:37 UTC, temyers commented on .gitignore
> +jest/
👍

2017-01-23 09:37 UTC, temyers commented on features/step_definitions/shout_steps.js
> +  var Shouty = require('../../lib/shouty');
👍

2017-01-23 11:13 UTC, merged

2017-01-23 11:13 UTC, jbpros commented
Thanks @temyers!